### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by clancyj4** [Blackend/Cyjon#120]
minivac2:~/cyjon/Cyjon$ nasm -f bin kernel/library.asm          -o build/library
kernel/library/bosu/header.asm:9: error: symbol `LIBRARY_BOSU_WINDOW_NAME_length' redefined
kernel/library/bosu/header.asm:10: error: symbol `LIBRARY_BOSU_WINDOW_BACKGROUND_color' redefined
kernel/library/bosu/header.asm:12: error: symbol `LIBRARY_BOSU_WINDOW_BORDER_THICKNESS_pixel' redefined
kernel/library/bosu/header.asm:13: error: symbol `LIBRARY_BOSU_WINDOW_BORDER_color' redefined
kernel/library/bosu/header.asm:16: error: symbol `LIBRARY_BOSU_WINDOW_FLAG_flush' redefined
kernel/library/bosu/header.asm:18: error: symbol `LIBRARY_BOSU_WINDOW_FLAG_visible' redefined
kernel/library/bosu/header.asm:19: error: symbol `LIBRARY_BOSU_WINDOW_FLAG_fixed_xy' redefined
kernel/library/bosu/header.asm:20: error: symbol `LIBRARY_BOSU_WINDOW_FLAG_fixed_z' redefined
kernel/library/bosu/header.asm:21: error: symbol `LIBRARY_BOSU_WINDOW_FLAG_fragile' redefined
kernel/library/bosu/header.asm:22: error: symbol `LIBRARY_BOSU_WINDOW_FLAG_arbiter' redefined
kernel/library/bosu/header.asm:23: error: symbol `LIBRARY_BOSU_WINDOW_FLAG_transparent' redefined
...kernel/library/bosu/header.asm:171: error: symbol `LIBRARY_BOSU_STRUCTURE_ELEMENT_CHAIN_size' redefined
kernel/library/terminal/header.asm:9: error: symbol `LIBRARY_TERMINAL_STRUCTURE' redefined
kernel/library/terminal/header.asm:24: error: symbol `LIBRARY_TERMINAL_STRUCTURE_size' redefined
kernel/library/terminal/header.asm:26: error: symbol `LIBRARY_TERMINAL_STURCTURE_CURSOR' redefined
kernel/library/terminal/header.asm:29: error: symbol `LIBRARY_TERMINAL_STURCTURE_CURSOR_size' redefined

**Comment by Blackend** [comment]
Is that "workbench" branch?On Mar 21, 2021 6:40 PM, Justin Clancy ***@***.***> wrote:
minivac2:~/cyjon/Cyjon$ nasm -f bin kernel/library.asm          -o build/library
kernel/library/bosu/header.asm:9: error: symbol LIBRARY_BOSU_WINDOW_NAME_length' redefined kernel/library/bosu/header.asm:10: error: symbol LIBRARY_BOSU_WINDOW_BACKGROUND_color' redefined
kernel/library/bosu/header.asm:12: error: symbol LIBRARY_BOSU_WINDOW_BORDER_THICKNESS_pixel' redefined kernel/library/bosu/header.asm:13: error: symbol LIBRARY_BOSU_WINDOW_BORDER_color' redefined
kernel/library/bosu/header.asm:16: error: symbol LIBRARY_BOSU_WINDOW_FLAG_flush' redefined kernel/library/bosu/header.asm:18: error: symbol LIBRARY_BOSU_WINDOW_FLAG_visible' redefined
kernel/library/bosu/header.asm:19: error: symbol LIBRARY_BOSU_WINDOW_FLAG_fixed_xy' redefined kernel/library/bosu/header.asm:20: error: symbol LIBRARY_BOSU_WINDOW_FLAG_fixed_z' redefined
kernel/library/bosu/header.asm:21: error: symbol LIBRARY_BOSU_WINDOW_FLAG_fragile' redefined kernel/library/bosu/header.asm:22: error: symbol LIBRARY_BOSU_WINDOW_FLAG_arbiter' redefined
kernel/library/bosu/header.asm:23: error: symbol LIBRARY_BOSU_WINDOW_FLAG_transparent' redefined ...kernel/library/bosu/header.asm:171: error: symbol LIBRARY_BOSU_STRUCTURE_ELEMENT_CHAIN_size' redefined
kernel/library/terminal/header.asm:9: error: symbol LIBRARY_TERMINAL_STRUCTURE' redefined kernel/library/terminal/header.asm:24: error: symbol LIBRARY_TERMINAL_STRUCTURE_size' redefined
kernel/library/terminal/header.asm:26: error: symbol LIBRARY_TERMINAL_STURCTURE_CURSOR' redefined kernel/library/terminal/header.asm:29: error: symbol LIBRARY_TERMINAL_STURCTURE_CURSOR_size' redefined

**Comment by Blackend** [comment]
Which version of nasm? I'm using stable right now, and everything is ok for both braches.

![obraz](https://user-images.githubusercontent.com/53617677/112096513-b4d6c600-8b9e-11eb-9661-cf0475ae5082.png)

**Comment by clancyj4** [comment]
I've got:

minivac2:~/cyjon/Cyjon$ nasm --version
NASM version 2.13.02

Is that too old?  It's standard on Ubuntu 18.04

**Comment by Blackend** [comment]
Yeah, that version will not work :)

![obraz](https://user-images.githubusercontent.com/53617677/112145314-7c54dd80-8bda-11eb-9965-fd7b5cab2804.png)

![obraz](https://user-images.githubusercontent.com/53617677/112145227-647d5980-8bda-11eb-94a4-ead0cd42dfbe.png)

**Comment by Blackend** [comment]
You need at least 2.14
