### ISSUE TITLE
How to port doom to Cyjon?

### ISSUE THREAD

**Issue by shoaib-jamal** [Blackend/Cyjon#124]
How can I port the Doom game to CyjonOS?

**Comment by Blackend** [comment]
At this point, I don't know myself, I haven't looked at how Doom uses the system's resources, Maybe this year I will check it :)

**Comment by shoaib-jamal** [comment]
Thanks for your time. Doom requires 4mb of Ram

**Comment by Blackend** [comment]
I will port Doom after finishing block_device/partition/filesystem support.

**Comment by shoaib-jamal** [comment]
ok
